Fix `dovi_tool` arch
The GitHub Actions workflow builds Docker container images for both
`linux/amd64` (`x86_64`) and `linux/arm64` (`aarch64`). However, the
Dockerfile is currently configured to always install `dovi_tool` built
for `linux/amd64` (`x86_64`). This means the `dovi_tool` installed in
the `linux/arm64` (`aarch64`) images is built for the incorrect arch.

This commit will correct the `dovi_tool` arch so that the correct build
of `dovi_tool` is installed on `linux/arm64` (`aarch64`). Docker offers
automatic platform ARGs in the global scope, including `TARGETARCH`, so
that the current arch can be determined within the Dockerfile. There is
additional programming needed to map between the Docker arch and the
arch specified in the `dovi_tool` download URL. Docker (via containerd)
normalizes arch names, so `x86_64` is always normalized to `amd64` and
`aarch64` is always normalized to `arm64`. The `dovi_tool` download URLs
use the un-normalized arch names. To avoid adding a `RUN` instruction
for setting the arch in the download URL, heredoc/here-doc syntax will
be used. The `ADD` will be replaced by a `wget` command in the heredoc.

https://docs.docker.com/reference/cli/docker/buildx/build/#platform
https://docs.docker.com/reference/dockerfile/#automatic-platform-args-in-the-global-scope
https://github.com/containerd/containerd/blob/v1.4.3/platforms/platforms.go#L63
https://github.com/moby/buildkit/blob/HEAD/frontend/dockerfile/docs/reference.md

diff --git a/dovi_tool/Dockerfile b/dovi_tool/Dockerfile
--- a/dovi_tool/Dockerfile
+++ b/dovi_tool/Dockerfile
@@ -1,6 +1,6 @@
 # syntax=docker/dockerfile:1
 FROM alpine:edge
-ARG DOVI_TOOL_ARCH=x86_64-unknown-linux-musl DOVI_TOOL_VERSION=2.1.2
+ARG DOVI_TOOL_VERSION=2.1.2 TARGETARCH
 
 LABEL org.opencontainers.image.description="Container image that can be used to run dovi_tool"
 LABEL org.opencontainers.image.licenses="CC0-1.0"
@@ -9,8 +9,17 @@ LABEL org.opencontainers.image.title="dovi_tool"
 LABEL org.opencontainers.image.url="https://github.com/br3ndonland/dovi_tool/pkgs/container/dovi_tool"
 
 RUN apk add --no-cache --upgrade jq mediainfo mkvtoolnix
-ADD https://github.com/quietvoid/dovi_tool/releases/download/${DOVI_TOOL_VERSION}/dovi_tool-${DOVI_TOOL_VERSION}-${DOVI_TOOL_ARCH}.tar.gz /tmp
-RUN tar -xvf /tmp/dovi_tool-${DOVI_TOOL_VERSION}-${DOVI_TOOL_ARCH}.tar.gz -C /usr/local/bin && rm -rf /tmp/*
+RUN <<HEREDOC
+case $TARGETARCH in
+amd64) DOVI_TOOL_ARCH="x86_64-unknown-linux-musl" ;;
+arm64) DOVI_TOOL_ARCH="aarch64-unknown-linux-musl" ;;
+*) printf "[ERROR] Unsupported \$TARGETARCH %s" "$TARGETARCH" && exit 1 ;;
+esac
+DOVI_TOOL_ARCHIVE="dovi_tool-${DOVI_TOOL_VERSION}-${DOVI_TOOL_ARCH}.tar.gz"
+wget -P /tmp https://github.com/quietvoid/dovi_tool/releases/download/${DOVI_TOOL_VERSION}/${DOVI_TOOL_ARCHIVE}
+tar -xvf /tmp/${DOVI_TOOL_ARCHIVE} -C /usr/local/bin
+rm -rf /tmp/*
+HEREDOC
 
 COPY --link ./dovi_tool.config.json /config/dovi_tool.config.json
 COPY --link --chmod=755 ./entrypoint.sh /usr/local/bin/entrypoint.sh
